### ISSUE TITLE
Add MOTD to the repo instead of reading it in from the host

### ISSUE THREAD

**Issue by flakrat** [uabrc/CRI_XCBC#18]
We need to change the current behavior of reading in `/etc/motd` to the default page to using a markdown file included in the repo.

The `/etc/motd` file isn't formatted for a web page.

**Comment by diedpigs** [comment]
Ansible role added, in my own environment. 
I used partitions variables from dev, prod variable split so might need to wait until that PR(jprorama/CRI_XCBC#65) is accepted.

**Comment by flakrat** [comment]
Looking at the file `/var/log/nginx/${USER}/error.log`, it logs the following error for a missing `announcement.md` file, which might be the right target for the MOTD code:

```console
App 171847 stdout: [2019-03-20 10:43:31 -0500 ]  WARN "Error parsing announcement file '/etc/ood/config/announcement.md': No such file or directory @ rb_sysopen - /etc/ood/config/announcement.md"
App 171847 stdout: [2019-03-20 10:43:31 -0500 ]  WARN "Error parsing announcement file '/etc/ood/config/announcement.yml': No such file or directory @ rb_sysopen - /etc/ood/config/announcement.yml"
```
