### ISSUE TITLE
OOD Presents Safari Warning about using Basic Auth, even though we are using Shib

### ISSUE THREAD

**Issue by flakrat** [uabrc/CRI_XCBC#19]
We are using Shibboleth for the authentication method, yet the following message is still triggered when using Safari web browser:

![image](https://user-images.githubusercontent.com/1587409/53440807-619be480-39d3-11e9-8ff5-3f2c67f5b8ef.png)

> As currently configured, the Cluster and Interactive Apps of Open OnDemand do not work with Safari. This is due to a bug in Safari with using websockets through servers protected using "Basic" auth. Open OnDemand can be installed with another authentication mechanism such as Shibboleth or OpenID Connect. If "Basic" auth is required, Mac users can connect with other browsers like Chrome or Firefox. Please contact this site’s technical support and report this message.

**Comment by diedpigs** [comment]
Solution: [OOD document](https://osc.github.io/ood-documentation/master/customization.html#disable-safari-warning-on-dashboard)
